name: 'Build'

on:
  workflow_dispatch:
  push:
    branches:
      - stable
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.1.1

      - name: Build
        run: |
          zig build -Doptimize=ReleaseSafe
